export const NFL_REGULAR_SEASON_WEEKS = 18 as const;

export type NflScheduleGame = {
  week: number;
  home: string;
  away: string;
  primetime?: boolean;
};

/** 2026 NFL regular-season slate (272 games). Home/away follow the NFL schedule. */
export const NFL_2026_GAMES: NflScheduleGame[] = [
  { week: 1, home: "CAR", away: "CHI" },
  { week: 1, home: "CIN", away: "TB" },
  { week: 1, home: "DET", away: "NO" },
  { week: 1, home: "HOU", away: "BUF" },
  { week: 1, home: "IND", away: "BAL" },
  { week: 1, home: "JAX", away: "CLE" },
  { week: 1, home: "KC", away: "DEN" },
  { week: 1, home: "LAC", away: "ARI" },
  { week: 1, home: "LAR", away: "SF" },
  { week: 1, home: "LV", away: "MIA" },
  { week: 1, home: "MIN", away: "GB" },
  { week: 1, home: "NYG", away: "DAL", primetime: true },
  { week: 1, home: "PHI", away: "WAS" },
  { week: 1, home: "PIT", away: "ATL" },
  { week: 1, home: "SEA", away: "NE", primetime: true },
  { week: 1, home: "TEN", away: "NYJ" },
  { week: 2, home: "ARI", away: "SEA" },
  { week: 2, home: "ATL", away: "CAR" },
  { week: 2, home: "BAL", away: "NO" },
  { week: 2, home: "BUF", away: "DET" },
  { week: 2, home: "CHI", away: "MIN" },
  { week: 2, home: "DAL", away: "WAS" },
  { week: 2, home: "DEN", away: "JAX" },
  { week: 2, home: "HOU", away: "CIN" },
  { week: 2, home: "KC", away: "IND" },
  { week: 2, home: "LAC", away: "LV" },
  { week: 2, home: "LAR", away: "NYG", primetime: true },
  { week: 2, home: "NE", away: "PIT" },
  { week: 2, home: "NYJ", away: "GB" },
  { week: 2, home: "SF", away: "MIA" },
  { week: 2, home: "TB", away: "CLE" },
  { week: 2, home: "TEN", away: "PHI" },
  { week: 3, home: "BUF", away: "LAC" },
  { week: 3, home: "CHI", away: "PHI", primetime: true },
  { week: 3, home: "CLE", away: "CAR" },
  { week: 3, home: "DAL", away: "BAL" },
  { week: 3, home: "DEN", away: "LAR" },
  { week: 3, home: "DET", away: "NYJ" },
  { week: 3, home: "GB", away: "ATL", primetime: true },
  { week: 3, home: "IND", away: "HOU" },
  { week: 3, home: "JAX", away: "NE" },
  { week: 3, home: "MIA", away: "KC" },
  { week: 3, home: "NO", away: "LV" },
  { week: 3, home: "NYG", away: "TEN" },
  { week: 3, home: "PIT", away: "CIN" },
  { week: 3, home: "SF", away: "ARI" },
  { week: 3, home: "TB", away: "MIN" },
  { week: 3, home: "WAS", away: "SEA" },
  { week: 4, home: "BAL", away: "TEN" },
  { week: 4, home: "BUF", away: "NE" },
  { week: 4, home: "CAR", away: "DET", primetime: true },
  { week: 4, home: "CHI", away: "NYJ" },
  { week: 4, home: "CIN", away: "JAX" },
  { week: 4, home: "CLE", away: "PIT" },
  { week: 4, home: "HOU", away: "DAL" },
  { week: 4, home: "LV", away: "KC" },
  { week: 4, home: "MIN", away: "MIA" },
  { week: 4, home: "NO", away: "ATL", primetime: true },
  { week: 4, home: "NYG", away: "ARI" },
  { week: 4, home: "PHI", away: "LAR" },
  { week: 4, home: "SEA", away: "LAC" },
  { week: 4, home: "SF", away: "DEN" },
  { week: 4, home: "TB", away: "GB" },
  { week: 4, home: "WAS", away: "IND" },
  { week: 5, home: "ARI", away: "DET" },
  { week: 5, home: "ATL", away: "BAL", primetime: true },
  { week: 5, home: "DAL", away: "TB" },
  { week: 5, home: "GB", away: "CHI" },
  { week: 5, home: "JAX", away: "PHI" },
  { week: 5, home: "LAC", away: "DEN" },
  { week: 5, home: "LAR", away: "BUF" },
  { week: 5, home: "MIA", away: "CIN" },
  { week: 5, home: "NE", away: "LV" },
  { week: 5, home: "NO", away: "MIN" },
  { week: 5, home: "NYJ", away: "CLE" },
  { week: 5, home: "PIT", away: "IND" },
  { week: 5, home: "SEA", away: "SF" },
  { week: 5, home: "TEN", away: "HOU" },
  { week: 5, home: "WAS", away: "NYG" },
  { week: 6, home: "ATL", away: "CHI" },
  { week: 6, home: "CLE", away: "BAL" },
  { week: 6, home: "DEN", away: "SEA" },
  { week: 6, home: "GB", away: "DAL", primetime: true },
  { week: 6, home: "IND", away: "TEN" },
  { week: 6, home: "JAX", away: "HOU" },
  { week: 6, home: "KC", away: "LAC" },
  { week: 6, home: "LAR", away: "ARI" },
  { week: 6, home: "LV", away: "BUF" },
  { week: 6, home: "NE", away: "NYJ" },
  { week: 6, home: "NYG", away: "NO" },
  { week: 6, home: "PHI", away: "CAR" },
  { week: 6, home: "SF", away: "WAS", primetime: true },
  { week: 6, home: "TB", away: "PIT" },
  { week: 7, home: "ARI", away: "DEN" },
  { week: 7, home: "ATL", away: "SF" },
  { week: 7, home: "BAL", away: "CIN" },
  { week: 7, home: "CAR", away: "TB" },
  { week: 7, home: "CHI", away: "NE", primetime: true },
  { week: 7, home: "DET", away: "GB" },
  { week: 7, home: "HOU", away: "NYG" },
  { week: 7, home: "LV", away: "LAR" },
  { week: 7, home: "MIN", away: "IND" },
  { week: 7, home: "NO", away: "PIT" },
  { week: 7, home: "NYJ", away: "MIA" },
  { week: 7, home: "PHI", away: "DAL", primetime: true },
  { week: 7, home: "SEA", away: "KC" },
  { week: 7, home: "TEN", away: "CLE" },
  { week: 8, home: "BUF", away: "BAL" },
  { week: 8, home: "CIN", away: "TEN" },
  { week: 8, home: "DAL", away: "ARI" },
  { week: 8, home: "DEN", away: "KC" },
  { week: 8, home: "DET", away: "MIN" },
  { week: 8, home: "GB", away: "CAR", primetime: true },
  { week: 8, home: "JAX", away: "IND" },
  { week: 8, home: "LAR", away: "LAC" },
  { week: 8, home: "MIA", away: "NE" },
  { week: 8, home: "NYJ", away: "LV" },
  { week: 8, home: "PIT", away: "CLE" },
  { week: 8, home: "SEA", away: "CHI", primetime: true },
  { week: 8, home: "TB", away: "ATL" },
  { week: 8, home: "WAS", away: "PHI", primetime: true },
  { week: 9, home: "ATL", away: "CIN" },
  { week: 9, home: "BAL", away: "JAX" },
  { week: 9, home: "CAR", away: "DEN" },
  { week: 9, home: "CHI", away: "TB", primetime: true },
  { week: 9, home: "IND", away: "DAL" },
  { week: 9, home: "KC", away: "NYJ" },
  { week: 9, home: "LAC", away: "HOU" },
  { week: 9, home: "MIA", away: "DET" },
  { week: 9, home: "MIN", away: "BUF" },
  { week: 9, home: "NE", away: "GB" },
  { week: 9, home: "NO", away: "CLE" },
  { week: 9, home: "PHI", away: "NYG" },
  { week: 9, home: "SEA", away: "ARI" },
  { week: 9, home: "SF", away: "LV" },
  { week: 9, home: "WAS", away: "LAR" },
  { week: 10, home: "ARI", away: "LAR" },
  { week: 10, home: "ATL", away: "KC" },
  { week: 10, home: "BAL", away: "LAC" },
  { week: 10, home: "CIN", away: "PIT" },
  { week: 10, home: "CLE", away: "HOU" },
  { week: 10, home: "DAL", away: "SF" },
  { week: 10, home: "DET", away: "NE" },
  { week: 10, home: "GB", away: "MIN" },
  { week: 10, home: "IND", away: "MIA" },
  { week: 10, home: "LV", away: "SEA" },
  { week: 10, home: "NO", away: "CAR" },
  { week: 10, home: "NYG", away: "WAS", primetime: true },
  { week: 10, home: "NYJ", away: "BUF" },
  { week: 10, home: "TEN", away: "JAX" },
  { week: 11, home: "BUF", away: "MIA" },
  { week: 11, home: "CAR", away: "BAL" },
  { week: 11, home: "CHI", away: "NO" },
  { week: 11, home: "DAL", away: "TEN" },
  { week: 11, home: "DEN", away: "LV" },
  { week: 11, home: "DET", away: "TB" },
  { week: 11, home: "HOU", away: "IND" },
  { week: 11, home: "KC", away: "ARI" },
  { week: 11, home: "LAC", away: "NYJ" },
  { week: 11, home: "NYG", away: "JAX" },
  { week: 11, home: "PHI", away: "PIT" },
  { week: 11, home: "SF", away: "MIN", primetime: true },
  { week: 11, home: "WAS", away: "CIN" },
  { week: 12, home: "ARI", away: "WAS" },
  { week: 12, home: "BUF", away: "KC" },
  { week: 12, home: "CIN", away: "NO" },
  { week: 12, home: "CLE", away: "LV" },
  { week: 12, home: "DAL", away: "PHI", primetime: true },
  { week: 12, home: "DET", away: "CHI", primetime: true },
  { week: 12, home: "HOU", away: "BAL" },
  { week: 12, home: "IND", away: "NYG" },
  { week: 12, home: "JAX", away: "TEN" },
  { week: 12, home: "LAC", away: "NE" },
  { week: 12, home: "LAR", away: "GB", primetime: true },
  { week: 12, home: "MIA", away: "NYJ" },
  { week: 12, home: "MIN", away: "ATL" },
  { week: 12, home: "PIT", away: "DEN" },
  { week: 12, home: "SF", away: "SEA" },
  { week: 12, home: "TB", away: "CAR", primetime: true },
  { week: 13, home: "ARI", away: "PHI" },
  { week: 13, home: "ATL", away: "DET" },
  { week: 13, home: "CHI", away: "JAX" },
  { week: 13, home: "CLE", away: "CIN" },
  { week: 13, home: "DEN", away: "MIA" },
  { week: 13, home: "LAR", away: "KC" },
  { week: 13, home: "MIN", away: "CAR" },
  { week: 13, home: "NE", away: "BUF" },
  { week: 13, home: "NO", away: "GB" },
  { week: 13, home: "NYG", away: "SF" },
  { week: 13, home: "PIT", away: "HOU" },
  { week: 13, home: "SEA", away: "DAL", primetime: true },
  { week: 13, home: "TB", away: "LAC" },
  { week: 13, home: "TEN", away: "WAS" },
  { week: 14, home: "BAL", away: "TB" },
  { week: 14, home: "CAR", away: "NO" },
  { week: 14, home: "CIN", away: "KC" },
  { week: 14, home: "CLE", away: "ATL" },
  { week: 14, home: "DET", away: "TEN" },
  { week: 14, home: "GB", away: "BUF" },
  { week: 14, home: "JAX", away: "PIT" },
  { week: 14, home: "LV", away: "LAC" },
  { week: 14, home: "MIA", away: "CHI" },
  { week: 14, home: "NE", away: "MIN", primetime: true },
  { week: 14, home: "NYJ", away: "DEN" },
  { week: 14, home: "PHI", away: "IND" },
  { week: 14, home: "SEA", away: "NYG" },
  { week: 14, home: "SF", away: "LAR" },
  { week: 14, home: "WAS", away: "HOU" },
  { week: 15, home: "ARI", away: "NYJ" },
  { week: 15, home: "BUF", away: "CHI" },
  { week: 15, home: "CAR", away: "CIN" },
  { week: 15, home: "GB", away: "MIA" },
  { week: 15, home: "HOU", away: "JAX" },
  { week: 15, home: "KC", away: "NE" },
  { week: 15, home: "LAC", away: "SF" },
  { week: 15, home: "LAR", away: "DAL" },
  { week: 15, home: "LV", away: "DEN" },
  { week: 15, home: "MIN", away: "DET", primetime: true },
  { week: 15, home: "NYG", away: "CLE" },
  { week: 15, home: "PHI", away: "SEA" },
  { week: 15, home: "PIT", away: "BAL" },
  { week: 15, home: "TB", away: "NO" },
  { week: 15, home: "TEN", away: "IND" },
  { week: 15, home: "WAS", away: "ATL" },
  { week: 16, home: "ATL", away: "TB" },
  { week: 16, home: "BAL", away: "CLE" },
  { week: 16, home: "CHI", away: "GB", primetime: true },
  { week: 16, home: "DAL", away: "JAX", primetime: true },
  { week: 16, home: "DEN", away: "BUF" },
  { week: 16, home: "DET", away: "NYG", primetime: true },
  { week: 16, home: "IND", away: "CIN" },
  { week: 16, home: "KC", away: "SF" },
  { week: 16, home: "LV", away: "TEN" },
  { week: 16, home: "MIA", away: "LAC" },
  { week: 16, home: "MIN", away: "WAS" },
  { week: 16, home: "NO", away: "ARI" },
  { week: 16, home: "NYJ", away: "NE" },
  { week: 16, home: "PHI", away: "HOU" },
  { week: 16, home: "PIT", away: "CAR" },
  { week: 16, home: "SEA", away: "LAR", primetime: true },
  { week: 17, home: "ARI", away: "LV" },
  { week: 17, home: "ATL", away: "NO" },
  { week: 17, home: "CAR", away: "SEA" },
  { week: 17, home: "CHI", away: "DET" },
  { week: 17, home: "CIN", away: "BAL" },
  { week: 17, home: "CLE", away: "IND" },
  { week: 17, home: "DAL", away: "NYG" },
  { week: 17, home: "GB", away: "HOU", primetime: true },
  { week: 17, home: "JAX", away: "WAS" },
  { week: 17, home: "LAC", away: "KC" },
  { week: 17, home: "MIA", away: "BUF" },
  { week: 17, home: "NE", away: "DEN" },
  { week: 17, home: "NYJ", away: "MIN" },
  { week: 17, home: "SF", away: "PHI", primetime: true },
  { week: 17, home: "TB", away: "LAR" },
  { week: 17, home: "TEN", away: "PIT" },
  { week: 18, home: "ARI", away: "SF" },
  { week: 18, home: "BAL", away: "PIT" },
  { week: 18, home: "BUF", away: "NYJ" },
  { week: 18, home: "CAR", away: "ATL" },
  { week: 18, home: "CIN", away: "CLE" },
  { week: 18, home: "DEN", away: "LAC" },
  { week: 18, home: "GB", away: "DET" },
  { week: 18, home: "HOU", away: "TEN" },
  { week: 18, home: "IND", away: "JAX" },
  { week: 18, home: "KC", away: "LV" },
  { week: 18, home: "LAR", away: "SEA" },
  { week: 18, home: "MIN", away: "CHI" },
  { week: 18, home: "NE", away: "MIA" },
  { week: 18, home: "NO", away: "TB" },
  { week: 18, home: "NYG", away: "PHI" },
  { week: 18, home: "WAS", away: "DAL" },
];

/** Bye week by franchise abbreviation. */
export const NFL_2026_BYES: Record<string, number> = {
  ARI: 14,
  ATL: 11,
  BAL: 13,
  BUF: 7,
  CAR: 5,
  CHI: 10,
  CIN: 6,
  CLE: 11,
  DAL: 14,
  DEN: 10,
  DET: 6,
  GB: 11,
  HOU: 8,
  IND: 13,
  JAX: 7,
  KC: 5,
  LAC: 7,
  LAR: 11,
  LV: 13,
  MIA: 6,
  MIN: 6,
  NE: 11,
  NO: 8,
  NYG: 8,
  NYJ: 13,
  PHI: 10,
  PIT: 9,
  SEA: 11,
  SF: 8,
  TB: 10,
  TEN: 9,
  WAS: 7,
};
