services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kml
      POSTGRES_PASSWORD: kml
      POSTGRES_DB: kings_madden_league
    volumes:
      - kml_pg_data:/var/lib/postgresql/data

volumes:
  kml_pg_data:
