import type { ContractPosition, ContractRules, MarketComp } from "./types";

/** Seeded from public 2026 reports (Spotrac / USA Today / SI). Commissioner should paste current Spotrac numbers as the market moves. */
export const DEFAULT_MARKET_COMPS: MarketComp[] = [
  {
    position: "QB",
    marketSetterName: "Patrick Mahomes",
    topOfMarketApy: 63.1,
    starterFloorApy: 38,
    typicalBonusRatio: 0.6,
    typicalLengthYears: 4,
    guaranteePercent: 0.65,
    sourceNote: "Aug 2026 · Mahomes $63.1M APY. Update from Spotrac QB page.",
  },
  {
    position: "RB",
    marketSetterName: "Saquon Barkley",
    topOfMarketApy: 20.6,
    starterFloorApy: 8,
    typicalBonusRatio: 0.35,
    typicalLengthYears: 3,
    guaranteePercent: 0.45,
    sourceNote: "Aug 2026 · Barkley $20.6M APY. RB deals stay short.",
  },
  {
    position: "WR",
    marketSetterName: "Jaxon Smith-Njigba",
    topOfMarketApy: 42.15,
    starterFloorApy: 18,
    typicalBonusRatio: 0.45,
    typicalLengthYears: 4,
    guaranteePercent: 0.5,
    sourceNote: "Aug 2026 · JSN $42.15M APY.",
  },
  {
    position: "TE",
    marketSetterName: "George Kittle",
    topOfMarketApy: 19.1,
    starterFloorApy: 10,
    typicalBonusRatio: 0.4,
    typicalLengthYears: 3,
    guaranteePercent: 0.5,
    sourceNote: "Aug 2026 · Kittle $19.1M APY.",
  },
  {
    position: "OL",
    marketSetterName: "Laremy Tunsil",
    topOfMarketApy: 30.1,
    starterFloorApy: 16,
    typicalBonusRatio: 0.4,
    typicalLengthYears: 4,
    guaranteePercent: 0.5,
    sourceNote: "Aug 2026 · Tunsil $30.1M APY (tackle market).",
  },
  {
    position: "EDGE",
    marketSetterName: "Will Anderson",
    topOfMarketApy: 50,
    starterFloorApy: 20,
    typicalBonusRatio: 0.45,
    typicalLengthYears: 4,
    guaranteePercent: 0.55,
    sourceNote: "Aug 2026 · Anderson $50M APY.",
  },
  {
    position: "DL",
    marketSetterName: "Chris Jones",
    topOfMarketApy: 31.75,
    starterFloorApy: 14,
    typicalBonusRatio: 0.4,
    typicalLengthYears: 3,
    guaranteePercent: 0.5,
    sourceNote: "Aug 2026 · Jones $31.75M APY.",
  },
  {
    position: "LB",
    marketSetterName: "Fred Warner",
    topOfMarketApy: 21,
    starterFloorApy: 10,
    typicalBonusRatio: 0.35,
    typicalLengthYears: 3,
    guaranteePercent: 0.45,
    sourceNote: "Aug 2026 · Warner $21M APY (off-ball).",
  },
  {
    position: "CB",
    marketSetterName: "Denzel Ward",
    topOfMarketApy: 31.1,
    starterFloorApy: 14,
    typicalBonusRatio: 0.4,
    typicalLengthYears: 4,
    guaranteePercent: 0.5,
    sourceNote: "Aug 2026 · Ward ~$31.1M APY; McDuffie $31M.",
  },
  {
    position: "S",
    marketSetterName: "Kyle Hamilton",
    topOfMarketApy: 25.1,
    starterFloorApy: 11,
    typicalBonusRatio: 0.35,
    typicalLengthYears: 3,
    guaranteePercent: 0.45,
    sourceNote: "Aug 2026 · Hamilton $25.1M APY.",
  },
  {
    position: "K",
    marketSetterName: "Ka'imi Fairbairn",
    topOfMarketApy: 6.5,
    starterFloorApy: 3.5,
    typicalBonusRatio: 0.25,
    typicalLengthYears: 4,
    guaranteePercent: 0.3,
    sourceNote: "Aug 2026 · Fairbairn $6.5M APY.",
  },
  {
    position: "P",
    marketSetterName: "Positional market",
    topOfMarketApy: 3.8,
    starterFloorApy: 2.2,
    typicalBonusRatio: 0.2,
    typicalLengthYears: 4,
    guaranteePercent: 0.25,
    sourceNote: "Aug 2026 · paste current Spotrac #1 punter APY.",
  },
];

export const DEFAULT_CONTRACT_RULES: ContractRules = {
  maxContractLength: 6,
  minContractLength: 2,
  maxTotalSalaryMillions: 200,
  maxSigningBonusMillions: 250,
  longContractYears: 7,
  overpayNoneMax: 1.15,
  overpayMinorMax: 1.5,
  overpayModerateMax: 2,
  moderateMarketMultiplier: 1.1,
  severeMarketMultiplier: 1.25,
  capPenaltyPercentOfOverage: 25,
  rookieScaleFallbackRatio: 0.35,
  depthMarketRatio: 0.55,
  defaultSevereResolution: "PENDING",
};

export const COMPS_BY_POSITION: Record<ContractPosition, MarketComp> =
  Object.fromEntries(
    DEFAULT_MARKET_COMPS.map((comp) => [comp.position, comp])
  ) as Record<ContractPosition, MarketComp>;
